// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "providerAutomatic": boolean;
      "providerCrossrefEnabled": boolean;
      "providerSemanticScholarEnabled": boolean;
      "providerOpenCitationsEnabled": boolean;
      "providerInspireEnabled": boolean;
      "providerOpenAlexEnabled": boolean;
      "openAlexAPIKey": string;
      "semanticScholarAPIKey": string;
      "showMetricTooltips": boolean;
      "automaticUpdates": boolean;
      "updateNewItems": boolean;
      "updateModifiedItems": boolean;
      "checkStaleOnStartup": boolean;
      "updateLibraryIDs": string;
      "cacheDays": number;
      "exactTitleFallback": boolean;
      "debugLogging": boolean;
      "graphAppearance": string;
      "graphAppearanceVersion": number;
    };
  }
}
